name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt nuitka

      - name: Build with Nuitka (Onefile)
        run: |
          python -m nuitka --onefile `
            --enable-plugin=pyside6 `
            --windows-console-mode=disable `
            --assume-yes-for-downloads `
            --windows-icon-from-ico=ImageAssets/app_icon.ico `
            --include-data-dir=ImageAssets/UI=ImageAssets/UI `
            --include-data-dir=ImageAssets/AppUI=ImageAssets/AppUI `
            --include-data-files=version=version `
            --include-data-files=source/utils/movement/model.npz=move_assets/model.npz `
            --include-data-files=source/utils/bridge/bridge.dll=move_assets/bridge.dll `
            --output-dir=build `
            App.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CGrinder-Windows
          path: build/app.exe
